export const options = [
  "Avocado",
  "Banana",
  "Brownie Bites",
  "Cherry",
  "Chocolate chips",
  "Chopped walnuts",
  "Coconut shavings",
  "Fresh strawberries",
  "Hot fudge",
  "Mini M&Ms",
  "Oreos",
  "Pickles",
  "Snickers",
  "Sprinkles",
  "Swedish fish",
  "Whipped cream",
];
